# change the checkpoint path here
spk_model_config_path = "./configs/spk_model_config/spkencoder.toml"
ckpt_path      = "./checkpoints/diffusion_model/diffusion_0400000.pt"
spk_model_ckpt_path = "./checkpoints/spk_model/spk_epoch400.pth"

model_name     = "Atten_unet_2d_3_v4"
t_mode         = "None"

[model_cfg.model_params]
hidden_size    = 72
emb_dim        = 128
num_heads      = 4
num_class      = 1

[model_cfg.stft_params]
n_fft      = 510
hop_length = 255
win_length = 510

[train_para]
use_amp        = true
learning_rate  = 1e-4
batch_size     = 12
num_workers    = 4
loss_type      = "MSE"
start_epoch    = 0
end_epoch      = 1001
log_every      = 25
ckpt_every     = 5000
diffusion_step = 200
beta_start     = 0.0001
beta_end       = 0.02

[dataset]
used_spk_num  = 100
tgt_len_sec   = 4
tgt_sr        = 16000
n_fft         = 1024
win_size      = 1024
hop_samples   = 256